
### Section A: Level 1 (Basic Queries)
-- Focus: SELECT, FROM, WHERE, ORDER BY, GROUP BY

-- 1. Data Exploration: Read all the data from the Supplier, Product, OrderItem, Orders, and Customer tables.
SELECT * FROM supplier;
SELECT * FROM product;
SELECT * FROM orderitem;
SELECT * FROM orders;
SELECT * FROM customer;

-- 2. Customer Demographics: Find the count of customers in each country, ordered from highest to lowest.
SELECT country, COUNT(id) AS count_cust 
FROM customer 
GROUP BY country 
ORDER BY count_cust DESC;

-- 3. Active Inventory: Display all products that are currently active (not discontinued).
SELECT * FROM product 
WHERE isdiscontinued = '1';

-- 4. Supplier Catalog: List all company names along with the names of the products they supply.
SELECT s.companyname, p.productname 
FROM supplier s 
JOIN product p ON s.id = p.supplierid;

-- 5. Regional Search: Find all customer information for those residing in 'Mexico'.
SELECT *
FROM customer
WHERE country = 'Mexico';

-- 6. High-Value Items: Identify the most expensive item ordered by each customer.
SELECT c.id AS customer_id, p.productname, p.unitprice 
FROM customer c 
JOIN orders o ON c.id = o.customerid
JOIN orderitem oi ON o.id = oi.orderid
JOIN product p ON p.id = oi.productid
WHERE (c.id, p.unitprice) IN (
    SELECT c.id, MAX(p.unitprice) 
    FROM product p
    JOIN orderitem oi ON oi.productid = p.id
    JOIN orders o ON o.id = oi.orderid
    JOIN customer c ON o.customerid = c.id
    GROUP BY c.id
);

-- 7. Top Suppliers: Find the Supplier ID that provides the highest number of products.
WITH max_p AS (
    SELECT s.id, COUNT(p.id) AS cnt_prod
    FROM supplier s 
    JOIN product p ON p.supplierid = s.id
    GROUP BY s.id
)
SELECT * FROM max_p 
WHERE cnt_prod IN (SELECT MAX(cnt_prod) FROM max_p);

-- 8. Order Trends: Display the count of orders placed each month and year.
SELECT YEAR(orderdate) AS year, MONTH(orderdate) AS month, COUNT(id) AS order_count 
FROM orders
GROUP BY YEAR(orderdate), MONTH(orderdate) 
ORDER BY year ASC, month ASC;

-- 9. Supplier Concentration: Which country has the maximum number of suppliers?
WITH max_c AS (
    SELECT country, COUNT(id) OVER(PARTITION BY country) AS count
    FROM supplier
)
SELECT DISTINCT * FROM max_c 
WHERE count IN (SELECT MAX(count) FROM max_c);

-- 10. Inactive Customers: Identify customers who have never placed an order.
SELECT * FROM customer
WHERE id NOT IN (SELECT customerid FROM orders);

### Section B: Level 2 (Intermediate Queries)
-- Focus: JOINS, AGGREGATIONS, LIMIT, WINDOW FUNCTIONS

-- 1. Product Demand: Arrange the Product IDs and Names based on the high demand by the customer.
SELECT p.id AS product_id, p.productname, SUM(oi.quantity) AS total_quantity
FROM orderitem oi 
JOIN product p ON p.id = oi.productid
GROUP BY p.id, p.productname 
ORDER BY total_quantity DESC;

-- 2. Annual Performance: Display the total number of orders delivered each year.
SELECT YEAR(orderdate) AS year, COUNT(id) AS total_orders 
FROM orders 
GROUP BY YEAR(orderdate);

-- 3. Revenue Analysis: Calculate the total revenue generated each year.
SELECT YEAR(orderdate) AS year, SUM(totalamount) AS total_revenue 
FROM orders 
GROUP BY YEAR(orderdate);

-- 4. Top Spender: Find the details of the customer who has spent the most money across all their orders.
SELECT c.*, SUM(totalamount) AS total_order_amount 
FROM customer c
JOIN orders o ON o.customerid = c.id
GROUP BY c.id 
ORDER BY SUM(totalamount) DESC 
LIMIT 1;

-- 5. Customer Ranking: List all customers and their total order amounts, ordered from highest to lowest.
SELECT c.*, SUM(totalamount) AS total_order_amount 
FROM customer c
JOIN orders o ON o.customerid = c.id
GROUP BY c.id 
ORDER BY SUM(totalamount) DESC;

-- 6. Order History: For each customer, list their current and previous order dates to see how frequently they do business.
SELECT c.id AS customerid, c.firstname, o.orderdate
FROM customer c 
JOIN orders o ON o.customerid = c.id
ORDER BY customerid, orderdate;

-- 7. Supplier Revenue: Identify the top 3 suppliers based on the total revenue generated by their products.
SELECT s.id AS supplierid, s.contactname, SUM(quantity * oi.unitprice) AS totalrevenue
FROM supplier s
JOIN product p ON s.id = p.supplierid
JOIN orderitem oi ON oi.productid = p.id
JOIN orders o ON o.id = oi.orderid
GROUP BY s.id, s.contactname 
ORDER BY totalrevenue DESC 
LIMIT 3;

-- 8. Customer Loyalty: Display the latest order date for each customer (excluding their very first order).
SELECT c.*, MAX(orderdate) AS latest_order_date
FROM customer c
JOIN orders o ON o.CustomerId = c.id
GROUP BY c.id;

-- 9. Order Details: For every order, display the Order ID, Product Name, and Supplier Name.
SELECT oi.orderid, p.productname, s.contactname AS suppliername
FROM supplier s 
JOIN product p ON p.supplierid = s.id
JOIN orderitem oi ON oi.productid = p.id
JOIN orders o ON o.id = oi.orderid;

### Section C: Level 3 (Advanced Queries)
-- Focus: WITH (CTE), COMPLEX JOINS, SUBQUERIES

-- 1. Bulk Buyers: Find customers who have ordered more than 10 products in a single order.
WITH product_ordered AS (
    SELECT DISTINCT c.*, COUNT(o.id) OVER(PARTITION BY c.id) AS count
    FROM customer c 
    JOIN orders o ON o.customerid = c.id
)
SELECT * FROM product_ordered 
WHERE count > 10 
ORDER BY count DESC;

-- 2. Small Orders: List all product details for items that were ordered with a quantity of exactly 1.
SELECT p.* 
FROM product p 
JOIN orderitem oi ON oi.productid = p.id 
WHERE quantity = 1;

-- 3. Premium Suppliers: Identify companies that supply products with a unit price above 100.
SELECT DISTINCT s.* 
FROM supplier s 
JOIN product p ON p.SupplierId = s.id
JOIN orderitem oi ON oi.productid = p.id 
WHERE oi.unitprice > 100;

-- 4. City-Based Networking: List customers who live in the same city and country, arranged by country.
SELECT DISTINCT c1.id, c1.firstname, c2.FirstName, c1.city, c1.country
FROM customer c1 
JOIN customer c2 ON (c1.city, c1.country) = (c2.city, c2.country)
WHERE c1.id <> c2.id
ORDER BY c1.country;

### Section D: Level 4 (Expert Queries)
-- Focus: COMPLEX CALCULATIONS, BUSINESS LOGIC
-- 1. Savings Analysis: The company offers discounts. Calculate the total amount saved in each order (Actual Price - Selling Price) and rank orders by total savings.
SELECT oi.orderid, SUM((p.unitprice - oi.unitprice) * oi.quantity) AS total_amount_saved
FROM product p 
JOIN orderitem oi ON p.id = oi.productid
GROUP BY oi.orderid 
ORDER BY total_amount_saved DESC;

### Market Research: Help a new supplier, Mr. Kavin, by identifying:
-- a. A list of high-demand products he should consider supplying.
SELECT p.productname, SUM(oi.quantity) AS total_demand
FROM product p
JOIN orderitem oi ON p.id = oi.productid
GROUP BY p.productname
ORDER BY total_demand DESC;

-- b. A list of his potential competitors for those products.
SELECT DISTINCT s.contactname, p.productname
FROM orderitem oi 
JOIN product p ON p.id = oi.productid
JOIN supplier s ON p.supplierid = s.id;







